name: Android CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Do NOT pass 'packages' here (that’s what keeps breaking)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-licenses: true

      # Install packages directly (each as its own argument)
      - name: Install Android packages (direct, safe)
        run: |
          yes | sdkmanager --licenses || true
          yes | sdkmanager \
            "platform-tools" \
            "build-tools;35.0.0" \
            "platforms;android-36" \
            "platforms;android-35"

      - name: Verify SDK contents (debug)
        run: |
          echo "SDK ROOT: $ANDROID_SDK_ROOT"
          yes | sdkmanager --list | head -200 || true

      - name: Prepare Gradle
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew --no-daemon clean assembleDebug
