name: Android CI
on: [push, pull_request]

env:
  ANDROID_PACKAGES: |
    cmdline-tools;latest
    platform-tools
    build-tools;34.0.0
    platforms;android-34
    platforms;android-30

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - uses: android-actions/setup-android@v3
        with:
          accept-licenses: true
          packages: ${{ env.ANDROID_PACKAGES }}

      - run: ./gradlew --no-daemon clean assembleDebug
