name: Android CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Installs SDK + the exact packages you need
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          # Accept SDK licenses so sdkmanager won't fail
          accept-licenses: true
          # Install packages (IMPORTANT: use a multiline block)
          packages: |
            platform-tools
            build-tools;34.0.0
            platforms;android-34
            platforms;android-30

      # (Optional) If you need NDK or cmake
      # - name: Install NDK and CMake
      #   uses: android-actions/setup-
