name: Android CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-licenses: true
          packages: |
            platform-tools
            build-tools;35.0.0
            platforms;android-36
            platforms;android-35

      - name: Build
        run: ./gradlew --no-daemon clean assembleDebug
